# Generated by Django 6.0.5 on 2026-07-17 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreinteret',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centres_interet', to='courses.categorie'),
        ),
        migrations.AddField(
            model_name='centreinteret',
            name='etudiant',
            field=models.ForeignKey(limit_choices_to={'role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='centres_interet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='centreinteret',
            unique_together={('etudiant', 'categorie')},
        ),
    ]
