# Generated by Django 6.0.6 on 2026-07-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='panier',
        ),
        migrations.AddField(
            model_name='paiement',
            name='cours',
            field=models.ManyToManyField(help_text='Cours couverts par ce paiement (un seul en achat direct, plusieurs en checkout panier).', related_name='paiements', to='courses.cours'),
        ),
    ]
